name: Build and Deploy

on: [workflow_dispatch, push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Install Quasar CLI
        run: npm install -g @quasar/cli

      - name: Build for production
        run: quasar build

      - name: Deploy to GitHub
        run: |
          echo "//<username>.github.io" > dist/spa/CNAME
          cd dist/spa
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy to GitHub"
          git remote add origin https://danuo:${{ secrets.SECRET_TOKEN }}@github.com/danuo/ravelights-ui-builds.git
          git push -u --force --quiet origin master
